org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.82
neo_version_range=[26.1.2.82,26.2)

mod_id=manufactory
mod_name=Manufactory
mod_license=LGPL-3.0-only
mod_version=1.0.0
mod_group_id=com.drakmyth.minecraft.manufactory
mod_authors=Drakmyth
mod_description=Manufactory, a tech mod focused on automation and resource generation.
mod_homepage=https://github.com/Drakmyth/Manufactory
mod_issues=https://github.com/Drakmyth/Manufactory/issues
mod_update_json=https://raw.githubusercontent.com/Drakmyth/Manufactory/master/update.json
